version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.3
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/log:/var/log/nginx
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SETUP_KIBANA_HOST: "http://kibana:5601"
volumes:
  es_data:
